images:
  brick: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/nixos-brick.png
  emote: https://raw.githubusercontent.com/redbrick/design-system/main/assets/logos/join-emote.png
society:
  name: Redbrick
  tagline: DCU's NixOS Society.
navigation:
  global:
    - text: Open Governance
      link: /open-governance/readme.html
    - text: Blog
      link: /blog/posts/2024-01-31-redbrick-maintenance-with-nomad.html
  blog:
    - text: Events
      tag: events
    - text: Admin Blog
      tag: admins
    - text: Tutorials
      tag: tutorial
    - text: Conferences
      tag: conferences
    - text: Newsletters
      tag: newsletter
  buttons:
    primary:
      text: Signup
      link: https://join.redbrick.dcu.ie
    secondary:
      text: Discord
      link: https://discord.redbrick.dcu.ie
drawer: navigation
home:
  hero:
    title:
      secondary: DCU's NixOS Society.
      primary: Become a Member.
    body: Redbrick was formed from a battered 386 PC (dubbed Nurse) and bits of borrowed memory - these days we spend our time running tech events for our members and deploying services. We’re open to everyone, regardless of computing level, who want to come and learn!
    buttons:
      primary:
        text: Signup
        link: https://join.redbrick.dcu.ie
      secondary:
        text: Discord
        link: https://discord.redbrick.dcu.ie
  cta:
    title: Don't Miss Out
    body: Redbrick hosts events for everything tech related - from computer programming tutorials to workshops with multinational tech companies.
    button:
      text: Signup
      link: https://join.redbrick.dcu.ie
  committee:
    - name: James Hackett
      position: 🪑 Chair
      username: distro
      image: /assets/img/committee/distro.jpg
    - name: Shane Whelan
      position: 🪑 Vice-Chair
      username: pluto
      image: /assets/img/committee/pluto.jpg
    - name: Jake Farrell
      position: 💌 Secretary
      username: cheese
      image: /assets/img/committee/cheese.png
    - name: Malavika Shanker
      position: 💸 Treasurer
      username: calcifer
      image: /assets/img/committee/calcifer.png
    - name: Philip Leonard
      position: 📢 PRO
      username: payne
      image: /assets/img/committee/payne.png
    - name: Ishita Gupta
      position: 🎨 GDO
      username: ishitag
      image: /assets/img/committee/ishitag.jpg
    - name: Dominic Connor
      position: 🚀 SysAdmin
      username: wizzdom
      image: /assets/img/committee/wizzdom.png
    - name: Cathal O'Grady
      position: 🚀 SysAdmin
      username: cathalog
      image: /assets/img/committee/cathalog.jpg
    - name: Gavin Holahan
      position: 🍼 SysAdmin
      username: hypnoant
      image: /assets/img/committee/hypnoant.png
    - name: Jed Hazaymeh
      position: 👾 Webmaster
      username: magma
      image: /assets/img/committee/magma.png
    - name: Ayden Jahola
      position: 🙌 Helpdesk
      username: ayden
      image: /assets/img/committee/ayden.png
    - name: Francis Baxter
      position: 🙌 Helpdesk
      username: fbaxter
      image: /assets/img/committee/fbaxter.png
    - name: Robert Healy
      position: 📅 Events Officer
      username: orb
      image: /assets/img/committee/orb.png
    - name: Stefania Ogun
      position: 📅 Events Officer
      username: stefania
      image: /assets/img/committee/stefania.jpg
    - name: Callum Browne
      position: 💎 Ordinary Member
      username: browner
      image: /assets/img/committee/browner.png
    - name: Daniel McEntee
      position: 💎 Ordinary Member
      username: kronos
      image: /assets/img/committee/kronos.png
    - name: Dennis Custiuc
      position: 🥇 First Year Rep.
      username: swooshy
      image: /assets/img/committee/swooshy.png
